### ISSUE TITLE
variable expansion in spack.yaml not working properly

### ISSUE THREAD

**Issue by jdomke** [LLNL/benchpark#226]
using configs/RCCS-Fugaku-Fujitsu-A64FX-TofuD/spack.yaml:
```
spack:
  packages:
    default-compiler:
      spack_spec: {default_comp} {sys_arch}
    default-mpi:
      spack_spec: fujitsu-mpi@{fj_comp_version}%{default_comp} {sys_arch}
```

default_comp is defined as 'clang@17.0.2'

it worked for `spack_spec: fujitsu-mpi@{fj_comp_version}%{default_comp} {sys_arch}`

but for `spack_spec: {default_comp} {sys_arch}` i'm getting the following error during `ramble ... setup`
```
==> Error: Error parsing yaml  in "/vol0005/mdt3/data/ra000020/u10016/benchpark.llvm/configs/RCCS-Fugaku-Fujitsu-A64FX-TofuD/spack.yaml", line 9, column 7: expected <block end>, but found '{'
```
