### ISSUE TITLE
Parameterizing the compiler to use for an experiment

### ISSUE THREAD

**Issue by pearce8** [LLNL/benchpark#238]
Update: @rfhaque Please verify that this works with the new experiment.py and system.py definitions.

Application.py can give suggestions on where an experiment might be run, but not requirements.  However, application.py could define a workload variable that can then be used in experiment variables.

Example of using a variable in the experiment to impact the build requirements:

https://github.com/LLNL/benchpark/tree/develop/experiments/amg2023/cuda/ramble.yaml
```
applications:
    amg2023:
      workloads:
        problem1:
          variables:
             cuda_arch: '{cuda_arch}'
spack:
    concretized: true
    packages:
      amg2023:
        spack_spec: amg2023@develop +mpi+cuda{modifier_spack_variant} cuda_arch=={cuda_arch} 
        compiler: default-compiler
```

How should we connect this to what is available on the system?

Note: environments are lazily rendered in Ramble, that is they are only rendered when the experiment phases are started.
