### ISSUE TITLE
Strong/weak/throughput experiments

### ISSUE THREAD

**Issue by pearce8** [LLNL/benchpark#338]
We want to be able to specify strong and weak scaling experiments:

- what stays constant,
- what gets zipped, 
- what range of process counts to use (i.e., 2 nodes to 16 nodes), 
- scaling_factor: either double the problem size when doubling resources, or keep the problem size the same.  

We also want to record the experiment name/specification to hand off to Caliper. 

Example: https://github.com/LLNL/benchpark/tree/develop/experiments/kripke/cuda

```
        experiments:
            kripke_cuda_strong_{n_nodes}_{ngroups}_{gs}_{nquad}_{ds}_{lorder}_{nzx}_{nzy}_{nzz}_{npx}_{npy}_{npz}:
              variants:
                package_manager: spack
              variables:
                ngroups: 64
                gs: 1
                nquad: 128
                ds: 128
                lorder: 4
                nzx: '64'
                nzy: '64'
                nzz: '32'
                npx: ['2', '2', '4', '4']
                npy: ['2', '2', '2', '4']
                npz: ['1', '2', '2', '2']
            kripke_cuda_weak_{n_nodes}_{ngroups}_{gs}_{nquad}_{ds}_{lorder}_{nzx}_{nzy}_{nzz}_{npx}_{npy}_{npz}:
              variants:
                package_manager: spack
              variables:
                ngroups: 64
                gs: 1
                nquad: 128
                ds: 128
                lorder: 4
                nzx: ['64', '64', '128', '128']
                nzy: ['64', '64', '64', '128']
                nzz: ['32', '64', '64', '64']
                npx: ['2', '2', '4', '4']
                npy: ['2', '2', '2', '4']
                npz: ['1', '2', '2', '2']
```

The Ramble command below outputs a json file with the experiment name expanded and not expanded:
```
ramble -D . workspace analyze --format json    
```

Experiments are variables in Ramble:
```
application.expander._variables
._variables['experiment_template_name']
application.expander.experiment_name
```
