### ISSUE TITLE
Suite: A set of experiments

### ISSUE THREAD

**Issue by pearce8** [LLNL/benchpark#567]
Notes and thoughts from a year ago are in #64.

Currently we have the following in dry runs/testing:
```
      - name: amg2023/cuda caliper=cuda,time lassen llnl-sierra cuda=11-8-0 compiler=clang-ibm
        uses: ./.github/actions/dynamic-dry-run
        with:
          benchmark_name: amg2023
          benchmark_mode: cuda
          benchmark_spec: amg2023+cuda caliper=cuda,time
          system_name: lassen
          system_spec: llnl-sierra cuda=11-8-0 compiler=clang-ibm
```

This is potentially problematic because:
- we are writing system parameters here, which may be a moving target
- we are writing experiment parameter here, which may also be a moving target
- we will duplicate this for dry runs, actual runs on platforms
