### ISSUE TITLE
Multiple providers for a virtual package

### ISSUE THREAD

**Issue by pearce8** [LLNL/benchpark#678]
Example: 
Blas is a virtual package with the following providers:
- intel-oneapi-mkl
- craylibsci
- rocsolver

If a system has more than one provider, spack will chose one.

Is the solution a variant on the system?  Why not?

In PR#617 this is accomplishes by:

```
    default-blas:
       pkg_spec: "{self.spec.variants["blas"][0]}"
     default-lapack:
       pkg_spec: "{self.spec.variants["lapack"][0]}"
```

How can we restrict Spack to using the provider we specified via a variant?             @scheibelp @becker33 

Found related Spack issue: https://github.com/spack/spack/issues/32657
